title: AR. Data Rules
avatar: /assets/images/avatar.jpg

# comma separated titles of sections 
sections: Statistics

collections:
  authors:
    output: true
  handbook:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      excerpt_separator: <!--more-->
  - scope:
      path: ""
      type: "handbook"
    values:
      layout: "handbookpage"
  - scope:
      path: ""
    values:
      layout: "default"