title: AR. Data Rules
avatar: /assets/images/avatar.jpg

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: "_posts/blog"
      type: "posts"
    values:
      layout: "post"
      excerpt_separator: <!--more-->
  - scope:
      path: "_posts/handbook"
      type: "posts"
    values:
      layout: "post"
      category: Handbook
      excerpt_separator: <!--more-->
      permalink: /:categories/:title:output_ext
  - scope:
      path: ""
    values:
      layout: "default"
      